TREATMENTS = {
    "Tomato___Early_blight": "Apply copper-based fungicide every 7-10 days. Remove infected leaves immediately.",
    "Tomato___Late_blight": "Use mancozeb or chlorothalonil fungicide. Avoid overhead irrigation.",
    "Tomato___Bacterial_spot": "Apply copper bactericide. Remove and destroy infected plant parts.",
    "Tomato___Leaf_Mold": "Improve air circulation. Apply fungicide containing chlorothalonil.",
    "Tomato___Septoria_leaf_spot": "Remove infected leaves. Apply fungicide with mancozeb or copper.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Apply miticide or neem oil spray. Increase humidity.",
    "Tomato___Target_Spot": "Apply fungicide. Remove infected leaves and plant debris.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "No cure. Remove infected plants. Control whitefly population.",
    "Tomato___Tomato_mosaic_virus": "No cure. Remove infected plants. Disinfect tools regularly.",
    "Tomato___healthy": "Your tomato plant looks healthy! Keep up good farming practices.",
    "Potato___Early_blight": "Apply mancozeb fungicide. Remove infected leaves. Ensure proper spacing.",
    "Potato___Late_blight": "Apply metalaxyl fungicide immediately. This spreads fast — act quickly.",
    "Potato___healthy": "Your potato plant looks healthy!",
    "Corn_(maize)___Common_rust_": "Apply fungicide with propiconazole. Plant rust-resistant varieties next season.",
    "Corn_(maize)___Northern_Leaf_Blight": "Apply fungicide. Remove crop debris after harvest.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Apply strobilurin fungicide. Improve air circulation.",
    "Corn_(maize)___healthy": "Your maize plant looks healthy!",
    "Apple___Apple_scab": "Apply captan or mancozeb fungicide during wet weather.",
    "Apple___Black_rot": "Prune infected branches. Apply copper fungicide.",
    "Apple___Cedar_apple_rust": "Apply myclobutanil fungicide. Remove nearby juniper trees if possible.",
    "Apple___healthy": "Your apple tree looks healthy!",
    "Grape___Black_rot": "Apply mancozeb fungicide. Remove mummified berries.",
    "Grape___Esca_(Black_Measles)": "No effective cure. Prune infected wood. Keep wounds protected.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Apply copper fungicide. Remove infected leaves.",
    "Grape___healthy": "Your grape plant looks healthy!",
    "Pepper,_bell___Bacterial_spot": "Apply copper bactericide. Avoid overhead watering.",
    "Pepper,_bell___healthy": "Your pepper plant looks healthy!",
    "Peach___Bacterial_spot": "Apply copper fungicide in spring. Avoid wetting leaves.",
    "Peach___healthy": "Your peach tree looks healthy!",
    "Strawberry___Leaf_scorch": "Apply captan fungicide. Remove infected leaves.",
    "Strawberry___healthy": "Your strawberry plant looks healthy!",
    "Squash___Powdery_mildew": "Apply sulfur or potassium bicarbonate spray. Improve air circulation.",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur fungicide. Prune for better air circulation.",
    "Cherry_(including_sour)___healthy": "Your cherry tree looks healthy!",
    "Orange___Haunglongbing_(Citrus_greening)": "No cure available. Remove infected trees to prevent spread.",
    "Blueberry___healthy": "Your blueberry plant looks healthy!",
    "Raspberry___healthy": "Your raspberry plant looks healthy!",
    "Soybean___healthy": "Your soybean plant looks healthy!",
}

PREVENTION = {
    "Tomato___Early_blight": "Rotate crops yearly. Use certified disease-free seeds. Mulch around plants.",
    "Tomato___Late_blight": "Plant resistant varieties. Avoid overhead irrigation. Ensure good drainage.",
    "Tomato___Bacterial_spot": "Use disease-free transplants. Avoid working in wet fields.",
    "Potato___Early_blight": "Use certified seed potatoes. Practice crop rotation every 3 years.",
    "Potato___Late_blight": "Plant resistant varieties. Monitor weather — blight spreads in cool wet conditions.",
    "Corn_(maize)___Common_rust_": "Plant early in the season. Use rust-resistant hybrid varieties.",
}